  version: '3.7'
  
  services:
    payroll:
      build:
        context: src/
        dockerfile: Payroll.WebApi/Dockerfile
      ports:
        - "8200:80"
      networks:
        - seafarers-network
    
    sqldata:
      image: mcr.microsoft.com/mssql/server:2019-CU9-ubuntu-16.04
      environment:
        - SA_PASSWORD=Marcura@2021
        - ACCEPT_EULA=Y
      ports:
        - "5433:1433"
      restart: unless-stopped
      volumes:
        - seafarer-sqldata:/var/opt/mssql
      networks:
        - seafarers-network
  
    elasticsearch:
      container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
      ports:
        - 9200:9200
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
      networks:
        - seafarers-network
  
    kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:7.9.2
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch
      environment:
        - ELASTICSEARCH_URL=http://localhost:9200
      networks:
        - seafarers-network
  
  networks:
    seafarers-network:
      driver: bridge
  
  volumes:
    seafarer-sqldata:
      external: false
    elasticsearch-data:
  
