using System.Collections.Generic;
using System.Linq;
using Payroll.Application.Common.Interfaces;

namespace Payroll.Infrastructure.Services
{
    public class CountryLookup : ICountryLookup
    {
        public bool IsKnownIsoCode(string isoCode)
        {
            var country = _countries.FirstOrDefault(c => c.IsoCode2Cc == isoCode);
            return country != default;
        }

        private static readonly IEnumerable<ICountryLookup.Country> _countries = new[]
        {
            ICountryLookup.Country.FromString(name: "Andorra", iso2Cc: "AD"),
            ICountryLookup.Country.FromString(name: "United Arab Emirates (the)", iso2Cc: "AE"),
            ICountryLookup.Country.FromString(name: "Afghanistan", iso2Cc: "AF"),
            ICountryLookup.Country.FromString(name: "Antigua and Barbuda", iso2Cc: "AG"),
            ICountryLookup.Country.FromString(name: "Anguilla", iso2Cc: "AI"),
            ICountryLookup.Country.FromString(name: "Albania", iso2Cc: "AL"),
            ICountryLookup.Country.FromString(name: "Armenia", iso2Cc: "AM"),
            ICountryLookup.Country.FromString(name: "Angola", iso2Cc: "AO"),
            ICountryLookup.Country.FromString(name: "Antarctica", iso2Cc: "AQ"),
            ICountryLookup.Country.FromString(name: "Argentina", iso2Cc: "AR"),
            ICountryLookup.Country.FromString(name: "American Samoa", iso2Cc: "AS"),
            ICountryLookup.Country.FromString(name: "Austria", iso2Cc: "AT"),
            ICountryLookup.Country.FromString(name: "Australia", iso2Cc: "AU"),
            ICountryLookup.Country.FromString(name: "Aruba", iso2Cc: "AW"),
            ICountryLookup.Country.FromString(name: "Åland Islands", iso2Cc: "AX"),
            ICountryLookup.Country.FromString(name: "Azerbaijan", iso2Cc: "AZ"),
            ICountryLookup.Country.FromString(name: "Bosnia and Herzegovina", iso2Cc: "BA"),
            ICountryLookup.Country.FromString(name: "Barbados", iso2Cc: "BB"),
            ICountryLookup.Country.FromString(name: "Bangladesh", iso2Cc: "BD"),
            ICountryLookup.Country.FromString(name: "Belgium", iso2Cc: "BE"),
            ICountryLookup.Country.FromString(name: "Burkina Faso", iso2Cc: "BF"),
            ICountryLookup.Country.FromString(name: "Bulgaria", iso2Cc: "BG"),
            ICountryLookup.Country.FromString(name: "Bahrain", iso2Cc: "BH"),
            ICountryLookup.Country.FromString(name: "Burundi", iso2Cc: "BI"),
            ICountryLookup.Country.FromString(name: "Benin", iso2Cc: "BJ"),
            ICountryLookup.Country.FromString(name: "Saint Barthélemy", iso2Cc: "BL"),
            ICountryLookup.Country.FromString(name: "Bermuda", iso2Cc: "BM"),
            ICountryLookup.Country.FromString(name: "Brunei Darussalam", iso2Cc: "BN"),
            ICountryLookup.Country.FromString(name: "Bolivia (Plurinational State of)", iso2Cc: "BO"),
            ICountryLookup.Country.FromString(name: "Bonaire, Sint Eustatius and Saba", iso2Cc: "BQ"),
            ICountryLookup.Country.FromString(name: "Brazil", iso2Cc: "BR"),
            ICountryLookup.Country.FromString(name: "Bahamas (the)", iso2Cc: "BS"),
            ICountryLookup.Country.FromString(name: "Bhutan", iso2Cc: "BT"),
            ICountryLookup.Country.FromString(name: "Bouvet Island", iso2Cc: "BV"),
            ICountryLookup.Country.FromString(name: "Botswana", iso2Cc: "BW"),
            ICountryLookup.Country.FromString(name: "Belarus", iso2Cc: "BY"),
            ICountryLookup.Country.FromString(name: "Belize", iso2Cc: "BZ"),
            ICountryLookup.Country.FromString(name: "Canada", iso2Cc: "CA"),
            ICountryLookup.Country.FromString(name: "Cocos (Keeling) Islands (the)", iso2Cc: "CC"),
            ICountryLookup.Country.FromString(name: "Congo (the Democratic Republic of the)", iso2Cc: "CD"),
            ICountryLookup.Country.FromString(name: "Central African Republic (the)", iso2Cc: "CF"),
            ICountryLookup.Country.FromString(name: "Congo (the)", iso2Cc: "CG"),
            ICountryLookup.Country.FromString(name: "Switzerland", iso2Cc: "CH"),
            ICountryLookup.Country.FromString(name: "Côte d'Ivoire", iso2Cc: "CI"),
            ICountryLookup.Country.FromString(name: "Cook Islands (the)", iso2Cc: "CK"),
            ICountryLookup.Country.FromString(name: "Chile", iso2Cc: "CL"),
            ICountryLookup.Country.FromString(name: "Cameroon", iso2Cc: "CM"),
            ICountryLookup.Country.FromString(name: "China", iso2Cc: "CN"),
            ICountryLookup.Country.FromString(name: "Colombia", iso2Cc: "CO"),
            ICountryLookup.Country.FromString(name: "Costa Rica", iso2Cc: "CR"),
            ICountryLookup.Country.FromString(name: "Cuba", iso2Cc: "CU"),
            ICountryLookup.Country.FromString(name: "Cabo Verde", iso2Cc: "CV"),
            ICountryLookup.Country.FromString(name: "Curaçao", iso2Cc: "CW"),
            ICountryLookup.Country.FromString(name: "Christmas Island", iso2Cc: "CX"),
            ICountryLookup.Country.FromString(name: "Cyprus", iso2Cc: "CY"),
            ICountryLookup.Country.FromString(name: "Czechia", iso2Cc: "CZ"),
            ICountryLookup.Country.FromString(name: "Germany", iso2Cc: "DE"),
            ICountryLookup.Country.FromString(name: "Djibouti", iso2Cc: "DJ"),
            ICountryLookup.Country.FromString(name: "Denmark", iso2Cc: "DK"),
            ICountryLookup.Country.FromString(name: "Dominica", iso2Cc: "DM"),
            ICountryLookup.Country.FromString(name: "Dominican Republic (the)", iso2Cc: "DO"),
            ICountryLookup.Country.FromString(name: "Algeria", iso2Cc: "DZ"),
            ICountryLookup.Country.FromString(name: "Ecuador", iso2Cc: "EC"),
            ICountryLookup.Country.FromString(name: "Estonia", iso2Cc: "EE"),
            ICountryLookup.Country.FromString(name: "Egypt", iso2Cc: "EG"),
            ICountryLookup.Country.FromString(name: "Western Sahara", iso2Cc: "EH"),
            ICountryLookup.Country.FromString(name: "Eritrea", iso2Cc: "ER"),
            ICountryLookup.Country.FromString(name: "Spain", iso2Cc: "ES"),
            ICountryLookup.Country.FromString(name: "Ethiopia", iso2Cc: "ET"),
            ICountryLookup.Country.FromString(name: "Finland", iso2Cc: "FI"),
            ICountryLookup.Country.FromString(name: "Fiji", iso2Cc: "FJ"),
            ICountryLookup.Country.FromString(name: "Falkland Islands (the) [Malvinas]", iso2Cc: "FK"),
            ICountryLookup.Country.FromString(name: "Micronesia (Federated States of)", iso2Cc: "FM"),
            ICountryLookup.Country.FromString(name: "Faroe Islands (the)", iso2Cc: "FO"),
            ICountryLookup.Country.FromString(name: "France", iso2Cc: "FR"),
            ICountryLookup.Country.FromString(name: "Gabon", iso2Cc: "GA"),
            ICountryLookup.Country.FromString(name: "United Kingdom of Great Britain & Northern Ireland", iso2Cc: "GB"),
            ICountryLookup.Country.FromString(name: "Grenada", iso2Cc: "GD"),
            ICountryLookup.Country.FromString(name: "Georgia", iso2Cc: "GE"),
            ICountryLookup.Country.FromString(name: "French Guiana", iso2Cc: "GF"),
            ICountryLookup.Country.FromString(name: "Guernsey", iso2Cc: "GG"),
            ICountryLookup.Country.FromString(name: "Ghana", iso2Cc: "GH"),
            ICountryLookup.Country.FromString(name: "Gibraltar", iso2Cc: "GI"),
            ICountryLookup.Country.FromString(name: "Greenland", iso2Cc: "GL"),
            ICountryLookup.Country.FromString(name: "Gambia (the)", iso2Cc: "GM"),
            ICountryLookup.Country.FromString(name: "Guinea", iso2Cc: "GN"),
            ICountryLookup.Country.FromString(name: "Guadeloupe", iso2Cc: "GP"),
            ICountryLookup.Country.FromString(name: "Equatorial Guinea", iso2Cc: "GQ"),
            ICountryLookup.Country.FromString(name: "Greece", iso2Cc: "GR"),
            ICountryLookup.Country.FromString(name: "South Georgia and the South Sandwich Islands", iso2Cc: "GS"),
            ICountryLookup.Country.FromString(name: "Guatemala", iso2Cc: "GT"),
            ICountryLookup.Country.FromString(name: "Guam", iso2Cc: "GU"),
            ICountryLookup.Country.FromString(name: "Guinea-Bissau", iso2Cc: "GW"),
            ICountryLookup.Country.FromString(name: "Guyana", iso2Cc: "GY"),
            ICountryLookup.Country.FromString(name: "Hong Kong", iso2Cc: "HK"),
            ICountryLookup.Country.FromString(name: "Heard Island and McDonald Islands", iso2Cc: "HM"),
            ICountryLookup.Country.FromString(name: "Honduras", iso2Cc: "HN"),
            ICountryLookup.Country.FromString(name: "Croatia", iso2Cc: "HR"),
            ICountryLookup.Country.FromString(name: "Haiti", iso2Cc: "HT"),
            ICountryLookup.Country.FromString(name: "Hungary", iso2Cc: "HU"),
            ICountryLookup.Country.FromString(name: "Indonesia", iso2Cc: "ID"),
            ICountryLookup.Country.FromString(name: "Ireland", iso2Cc: "IE"),
            ICountryLookup.Country.FromString(name: "Israel", iso2Cc: "IL"),
            ICountryLookup.Country.FromString(name: "Isle of Man", iso2Cc: "IM"),
            ICountryLookup.Country.FromString(name: "India", iso2Cc: "IN"),
            ICountryLookup.Country.FromString(name: "British Indian Ocean Territory (the)", iso2Cc: "IO"),
            ICountryLookup.Country.FromString(name: "Iraq", iso2Cc: "IQ"),
            ICountryLookup.Country.FromString(name: "Iran (Islamic Republic of)", iso2Cc: "IR"),
            ICountryLookup.Country.FromString(name: "Iceland", iso2Cc: "IS"),
            ICountryLookup.Country.FromString(name: "Italy", iso2Cc: "IT"),
            ICountryLookup.Country.FromString(name: "Jersey", iso2Cc: "JE"),
            ICountryLookup.Country.FromString(name: "Jamaica", iso2Cc: "JM"),
            ICountryLookup.Country.FromString(name: "Jordan", iso2Cc: "JO"),
            ICountryLookup.Country.FromString(name: "Japan", iso2Cc: "JP"),
            ICountryLookup.Country.FromString(name: "Kenya", iso2Cc: "KE"),
            ICountryLookup.Country.FromString(name: "Kyrgyzstan", iso2Cc: "KG"),
            ICountryLookup.Country.FromString(name: "Cambodia", iso2Cc: "KH"),
            ICountryLookup.Country.FromString(name: "Kiribati", iso2Cc: "KI"),
            ICountryLookup.Country.FromString(name: "Comoros (the)", iso2Cc: "KM"),
            ICountryLookup.Country.FromString(name: "Saint Kitts and Nevis", iso2Cc: "KN"),
            ICountryLookup.Country.FromString(name: "Korea (the Democratic People's Republic of)", iso2Cc: "KP"),
            ICountryLookup.Country.FromString(name: "Korea (the Republic of)", iso2Cc: "KR"),
            ICountryLookup.Country.FromString(name: "Kuwait", iso2Cc: "KW"),
            ICountryLookup.Country.FromString(name: "Cayman Islands (the)", iso2Cc: "KY"),
            ICountryLookup.Country.FromString(name: "Kazakhstan", iso2Cc: "KZ"),
            ICountryLookup.Country.FromString(name: "Lao People's Democratic Republic (the)", iso2Cc: "LA"),
            ICountryLookup.Country.FromString(name: "Lebanon", iso2Cc: "LB"),
            ICountryLookup.Country.FromString(name: "Saint Lucia", iso2Cc: "LC"),
            ICountryLookup.Country.FromString(name: "Liechtenstein", iso2Cc: "LI"),
            ICountryLookup.Country.FromString(name: "Sri Lanka", iso2Cc: "LK"),
            ICountryLookup.Country.FromString(name: "Liberia", iso2Cc: "LR"),
            ICountryLookup.Country.FromString(name: "Lesotho", iso2Cc: "LS"),
            ICountryLookup.Country.FromString(name: "Lithuania", iso2Cc: "LT"),
            ICountryLookup.Country.FromString(name: "Luxembourg", iso2Cc: "LU"),
            ICountryLookup.Country.FromString(name: "Latvia", iso2Cc: "LV"),
            ICountryLookup.Country.FromString(name: "Libya", iso2Cc: "LY"),
            ICountryLookup.Country.FromString(name: "Morocco", iso2Cc: "MA"),
            ICountryLookup.Country.FromString(name: "Monaco", iso2Cc: "MC"),
            ICountryLookup.Country.FromString(name: "Moldova (the Republic of)", iso2Cc: "MD"),
            ICountryLookup.Country.FromString(name: "Montenegro", iso2Cc: "ME"),
            ICountryLookup.Country.FromString(name: "Saint Martin (French part)", iso2Cc: "MF"),
            ICountryLookup.Country.FromString(name: "Madagascar", iso2Cc: "MG"),
            ICountryLookup.Country.FromString(name: "Marshall Islands (the)", iso2Cc: "MH"),
            ICountryLookup.Country.FromString(name: "Republic of North Macedonia", iso2Cc: "MK"),
            ICountryLookup.Country.FromString(name: "Mali", iso2Cc: "ML"),
            ICountryLookup.Country.FromString(name: "Myanmar", iso2Cc: "MM"),
            ICountryLookup.Country.FromString(name: "Mongolia", iso2Cc: "MN"),
            ICountryLookup.Country.FromString(name: "Macao", iso2Cc: "MO"),
            ICountryLookup.Country.FromString(name: "Northern Mariana Islands (the)", iso2Cc: "MP"),
            ICountryLookup.Country.FromString(name: "Martinique", iso2Cc: "MQ"),
            ICountryLookup.Country.FromString(name: "Mauritania", iso2Cc: "MR"),
            ICountryLookup.Country.FromString(name: "Montserrat", iso2Cc: "MS"),
            ICountryLookup.Country.FromString(name: "Malta", iso2Cc: "MT"),
            ICountryLookup.Country.FromString(name: "Mauritius", iso2Cc: "MU"),
            ICountryLookup.Country.FromString(name: "Maldives", iso2Cc: "MV"),
            ICountryLookup.Country.FromString(name: "Malawi", iso2Cc: "MW"),
            ICountryLookup.Country.FromString(name: "Mexico", iso2Cc: "MX"),
            ICountryLookup.Country.FromString(name: "Malaysia", iso2Cc: "MY"),
            ICountryLookup.Country.FromString(name: "Mozambique", iso2Cc: "MZ"),
            ICountryLookup.Country.FromString(name: "Namibia", iso2Cc: "NA"),
            ICountryLookup.Country.FromString(name: "New Caledonia", iso2Cc: "NC"),
            ICountryLookup.Country.FromString(name: "Niger (the)", iso2Cc: "NE"),
            ICountryLookup.Country.FromString(name: "Norfolk Island", iso2Cc: "NF"),
            ICountryLookup.Country.FromString(name: "Nigeria", iso2Cc: "NG"),
            ICountryLookup.Country.FromString(name: "Nicaragua", iso2Cc: "NI"),
            ICountryLookup.Country.FromString(name: "Netherlands (the)", iso2Cc: "NL"),
            ICountryLookup.Country.FromString(name: "Norway", iso2Cc: "NO"),
            ICountryLookup.Country.FromString(name: "Nepal", iso2Cc: "NP"),
            ICountryLookup.Country.FromString(name: "Nauru", iso2Cc: "NR"),
            ICountryLookup.Country.FromString(name: "Niue", iso2Cc: "NU"),
            ICountryLookup.Country.FromString(name: "New Zealand", iso2Cc: "NZ"),
            ICountryLookup.Country.FromString(name: "Oman", iso2Cc: "OM"),
            ICountryLookup.Country.FromString(name: "Panama", iso2Cc: "PA"),
            ICountryLookup.Country.FromString(name: "Peru", iso2Cc: "PE"),
            ICountryLookup.Country.FromString(name: "French Polynesia", iso2Cc: "PF"),
            ICountryLookup.Country.FromString(name: "Papua New Guinea", iso2Cc: "PG"),
            ICountryLookup.Country.FromString(name: "Philippines (the)", iso2Cc: "PH"),
            ICountryLookup.Country.FromString(name: "Pakistan", iso2Cc: "PK"),
            ICountryLookup.Country.FromString(name: "Poland", iso2Cc: "PL"),
            ICountryLookup.Country.FromString(name: "Saint Pierre and Miquelon", iso2Cc: "PM"),
            ICountryLookup.Country.FromString(name: "Pitcairn", iso2Cc: "PN"),
            ICountryLookup.Country.FromString(name: "Puerto Rico", iso2Cc: "PR"),
            ICountryLookup.Country.FromString(name: "Palestine, State of", iso2Cc: "PS"),
            ICountryLookup.Country.FromString(name: "Portugal", iso2Cc: "PT"),
            ICountryLookup.Country.FromString(name: "Palau", iso2Cc: "PW"),
            ICountryLookup.Country.FromString(name: "Paraguay", iso2Cc: "PY"),
            ICountryLookup.Country.FromString(name: "Qatar", iso2Cc: "QA"),
            ICountryLookup.Country.FromString(name: "Réunion", iso2Cc: "RE"),
            ICountryLookup.Country.FromString(name: "Romania", iso2Cc: "RO"),
            ICountryLookup.Country.FromString(name: "Serbia", iso2Cc: "RS"),
            ICountryLookup.Country.FromString(name: "Russian Federation (the)", iso2Cc: "RU"),
            ICountryLookup.Country.FromString(name: "Rwanda", iso2Cc: "RW"),
            ICountryLookup.Country.FromString(name: "Saudi Arabia", iso2Cc: "SA"),
            ICountryLookup.Country.FromString(name: "Solomon Islands", iso2Cc: "SB"),
            ICountryLookup.Country.FromString(name: "Seychelles", iso2Cc: "SC"),
            ICountryLookup.Country.FromString(name: "Sudan (the)", iso2Cc: "SD"),
            ICountryLookup.Country.FromString(name: "Sweden", iso2Cc: "SE"),
            ICountryLookup.Country.FromString(name: "Singapore", iso2Cc: "SG"),
            ICountryLookup.Country.FromString(name: "Saint Helena, Ascension and Tristan da Cunha", iso2Cc: "SH"),
            ICountryLookup.Country.FromString(name: "Slovenia", iso2Cc: "SI"),
            ICountryLookup.Country.FromString(name: "Svalbard and Jan Mayen", iso2Cc: "SJ"),
            ICountryLookup.Country.FromString(name: "Slovakia", iso2Cc: "SK"),
            ICountryLookup.Country.FromString(name: "Sierra Leone", iso2Cc: "SL"),
            ICountryLookup.Country.FromString(name: "San Marino", iso2Cc: "SM"),
            ICountryLookup.Country.FromString(name: "Senegal", iso2Cc: "SN"),
            ICountryLookup.Country.FromString(name: "Somalia", iso2Cc: "SO"),
            ICountryLookup.Country.FromString(name: "Suriname", iso2Cc: "SR"),
            ICountryLookup.Country.FromString(name: "South Sudan", iso2Cc: "SS"),
            ICountryLookup.Country.FromString(name: "Sao Tome and Principe", iso2Cc: "ST"),
            ICountryLookup.Country.FromString(name: "El Salvador", iso2Cc: "SV"),
            ICountryLookup.Country.FromString(name: "Sint Maarten (Dutch part)", iso2Cc: "SX"),
            ICountryLookup.Country.FromString(name: "Syrian Arab Republic", iso2Cc: "SY"),
            ICountryLookup.Country.FromString(name: "Eswatini", iso2Cc: "SZ"),
            ICountryLookup.Country.FromString(name: "Turks and Caicos Islands (the)", iso2Cc: "TC"),
            ICountryLookup.Country.FromString(name: "Chad", iso2Cc: "TD"),
            ICountryLookup.Country.FromString(name: "French Southern Territories (the)", iso2Cc: "TF"),
            ICountryLookup.Country.FromString(name: "Togo", iso2Cc: "TG"),
            ICountryLookup.Country.FromString(name: "Thailand", iso2Cc: "TH"),
            ICountryLookup.Country.FromString(name: "Tajikistan", iso2Cc: "TJ"),
            ICountryLookup.Country.FromString(name: "Tokelau", iso2Cc: "TK"),
            ICountryLookup.Country.FromString(name: "Timor-Leste", iso2Cc: "TL"),
            ICountryLookup.Country.FromString(name: "Turkmenistan", iso2Cc: "TM"),
            ICountryLookup.Country.FromString(name: "Tunisia", iso2Cc: "TN"),
            ICountryLookup.Country.FromString(name: "Tonga", iso2Cc: "TO"),
            ICountryLookup.Country.FromString(name: "Turkey", iso2Cc: "TR"),
            ICountryLookup.Country.FromString(name: "Trinidad and Tobago", iso2Cc: "TT"),
            ICountryLookup.Country.FromString(name: "Tuvalu", iso2Cc: "TV"),
            ICountryLookup.Country.FromString(name: "Taiwan (Province of China)", iso2Cc: "TW"),
            ICountryLookup.Country.FromString(name: "Tanzania, United Republic of", iso2Cc: "TZ"),
            ICountryLookup.Country.FromString(name: "Ukraine", iso2Cc: "UA"),
            ICountryLookup.Country.FromString(name: "Uganda", iso2Cc: "UG"),
            ICountryLookup.Country.FromString(name: "United States Minor Outlying Islands (the)", iso2Cc: "UM"),
            ICountryLookup.Country.FromString(name: "United States of America (the)", iso2Cc: "US"),
            ICountryLookup.Country.FromString(name: "Uruguay", iso2Cc: "UY"),
            ICountryLookup.Country.FromString(name: "Uzbekistan", iso2Cc: "UZ"),
            ICountryLookup.Country.FromString(name: "Holy See (the)", iso2Cc: "VA"),
            ICountryLookup.Country.FromString(name: "Saint Vincent and the Grenadines", iso2Cc: "VC"),
            ICountryLookup.Country.FromString(name: "Venezuela (Bolivarian Republic of)", iso2Cc: "VE"),
            ICountryLookup.Country.FromString(name: "Virgin Islands (British)", iso2Cc: "VG"),
            ICountryLookup.Country.FromString(name: "Virgin Islands (U.S.)", iso2Cc: "VI"),
            ICountryLookup.Country.FromString(name: "Viet Nam", iso2Cc: "VN"),
            ICountryLookup.Country.FromString(name: "Vanuatu", iso2Cc: "VU"),
            ICountryLookup.Country.FromString(name: "Wallis and Futuna", iso2Cc: "WF"),
            ICountryLookup.Country.FromString(name: "Samoa", iso2Cc: "WS"),
            ICountryLookup.Country.FromString(name: "Yemen", iso2Cc: "YE"),
            ICountryLookup.Country.FromString(name: "Mayotte", iso2Cc: "YT"),
            ICountryLookup.Country.FromString(name: "South Africa", iso2Cc: "ZA"),
            ICountryLookup.Country.FromString(name: "Zambia", iso2Cc: "ZM"),
            ICountryLookup.Country.FromString(name: "Zimbabwe", iso2Cc: "ZW")
        };
    }
}